on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: |
          npm install -g vsce
          npm install
      - name: Self sast-scan
        uses: ShiftLeftSecurity/scan-action@master
        with:
          output: reports
          type: nodejs,credscan,depscan
        env:
          DISABLE_TELEMETRY: true
          WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create package
        run: |
          sh release.sh
      - name: Upload package
        uses: actions/upload-artifact@v1.0.0
        with:
          name: scan-vscode-dev
          path: dist
